# FPL Optimisation

In [3]:
import requests
import pandas as pd
import numpy as np
from fpl import FPL

import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import clear_output

%matplotlib inline
%config InlineBackend.figure_format='retina'

sns.set_style("darkgrid")

## Extracting data

### Extracting all Players and Teams data

In [4]:
#game data
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'

r = requests.get(url)

json_data = r.json()

player_df = pd.DataFrame(json_data['elements'])
player_types_df = pd.DataFrame(json_data['element_types'])
teams_df = pd.DataFrame(json_data['teams'])

json_data.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

events = summary stats for each gameweek  
game_settings = overall settings for the game  
phases = start and stop gameweeks for months  
teams = summary data about the teams - seemingly no points/league table filled in though  
total_players = number of total players globally  
elements = all players and some summary stats  
element_stats = mapping for player stats labels eg. {'label': 'Goals scored', 'name': 'goals_scored'}  
element_types = positions and the rules per position

### Extracting Fixtures

In [5]:
#game data
url = 'https://fantasy.premierleague.com/api/fixtures/'

r = requests.get(url)

json_data = r.json()

fixtures_df = pd.DataFrame(json_data)

### Extracting My Team

In [6]:
team_id = '1409005'
url2 = 'https://fantasy.premierleague.com/api/my-team/{}'.format(team_id)

In [7]:
password = input('Password=')
session = requests.session()

url = 'https://users.premierleague.com/accounts/login/'
payload = {
 'password': password,
 'login': 'lukebetham@hotmail.com',
 'redirect_uri': 'https://fantasy.premierleague.com/a/login',
 'app': 'plfpl-web'
}

session.post(url, data=payload)

response = session.get(url2)

json = response.json()
clear_output()
del password

myteam_df = pd.DataFrame(json['picks'])

## Joining and cleaning

In [32]:
player_df['value']=player_df['total_points']/player_df['now_cost']
player_clean_df = player_df[['id','web_name','code','element_type','team',
           'total_points','value','now_cost','points_per_game','form','selected_by_percent','minutes',
           'transfers_in_event', 'transfers_out_event',
           'chance_of_playing_next_round','news','status',
           'bps','goals_scored','assists', 'clean_sheets', 'goals_conceded', 'own_goals',
           'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards','saves']]

In [33]:
player_clean_df

,id,web_name,code,element_type,team,total_points,value,now_cost,points_per_game,form,...,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves
0,1,Özil,37605,3,1,0,0.000000,68,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,Sokratis,39476,2,1,0,0.000000,48,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,David Luiz,41270,2,1,9,0.166667,54,1.1,0.3,...,0,0,0,9,0,0,0,0,0,0
3,4,Aubameyang,54694,3,1,50,0.438596,114,3.6,2.5,...,3,1,4,16,1,0,0,2,0,0
4,5,Cédric,58822,2,1,1,0.021739,46,1.0,0.2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,610,Corbeanu,443296,3,20,0,0.000000,45,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
612,611,Perry,232361,3,20,0,0.000000,45,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
613,614,Cundle,245923,3,20,0,0.000000,45,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
614,615,Richards,437688,2,20,0,0.000000,40,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
615,616,Marques,481626,2,20,0,0.000000,40,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
fixtures_df["home_win"]=(fixtures_df.team_a_score-fixtures_df.team_h_score).apply(lambda x: 1 if x < 0 else 0)
fixtures_df["draw"]=(fixtures_df.team_a_score-fixtures_df.team_h_score).apply(lambda x: 1 if x == 0 else 0)
fixtures_df["away_win"]=(fixtures_df.team_a_score-fixtures_df.team_h_score).apply(lambda x: 1 if x > 0 else 0)
fixtures_df["home_cleansheet"] = fixtures_df.team_a_score.apply(lambda x: 1 if x == 0 else 0)
fixtures_df["home_scored"] = fixtures_df.team_h_score.apply(lambda x: 1 if x != 0 else 0)
fixtures_df["away_cleansheet"] = fixtures_df.team_h_score.apply(lambda x: 1 if x == 0 else 0)
fixtures_df["away_scored"] = fixtures_df.team_a_score.apply(lambda x: 1 if x != 0 else 0)

In [74]:
away_df = fixtures_df[fixtures_df['finished']==True].groupby('team_a').agg({'finished':'count',
                                                                            'away_win':'sum',
                                                                            "team_a_score":'sum',
                                                                            "team_h_score":'sum',
                                                                            "away_cleansheet":'sum',
                                                                            "away_scored":'sum'})
home_df = fixtures_df[fixtures_df['finished']==True].groupby('team_h').agg({'finished':'count',
                                                                            'home_win':'sum',
                                                                            "team_h_score":'sum',
                                                                            "team_a_score":'sum',
                                                                            "home_cleansheet":'sum',
                                                                            "away_scored":'sum'})
away_df.columns = ["played_away","won_away",'score_away','conceded_away','cleansheet_away','scored_away']
home_df.columns = ["played_home","won_home",'score_home','conceded_home','cleansheet_home','scored_home']
results_df = pd.merge(home_df,away_df,left_index=True,right_index=True)

In [84]:
results_df['win_ratio'] = (results_df['won_home']+results_df['won_away'])/ \
                            (results_df['played_home']+results_df['played_away'])
results_df['scored_ratio'] = (results_df['scored_away']+results_df['scored_home'])/ \
                            (results_df['played_home']+results_df['played_away'])
results_df['cleansheet_ratio'] = (results_df['cleansheet_away']+results_df['cleansheet_home'])/ \
                            (results_df['played_home']+results_df['played_away'])
results_df['goals_per_match'] = (results_df['score_home']+results_df['score_away'])/ \
                            (results_df['played_home']+results_df['played_away'])
results_df['home_away_bias'] = (results_df['won_home']/results_df['played_home'])- \
                                (results_df['won_away']/results_df['played_away'])
results_df = pd.merge(teams_df[['id','name']],results_df.reset_index(),left_on='id',right_on='team_h')

In [85]:
results_df

,id,name,team_h,played_home,won_home,score_home,conceded_home,cleansheet_home,scored_home,played_away,won_away,score_away,conceded_away,cleansheet_away,scored_away,win_ratio,scored_ratio,cleansheet_ratio,goals_per_match,home_away_bias
0,1,Arsenal,1,8,3,9.0,11.0,0,8,8,3,7.0,8.0,4,5,0.375000,0.812500,0.250000,1.000000,0.000000
1,2,Aston Villa,2,7,3,15.0,11.0,3,4,7,5,13.0,3.0,5,7,0.571429,0.785714,0.571429,2.000000,-0.285714
2,3,Brighton,3,8,0,7.0,12.0,1,7,8,2,11.0,13.0,2,6,0.125000,0.812500,0.187500,1.125000,-0.250000
3,4,Burnley,4,7,3,5.0,7.0,2,5,8,1,4.0,13.0,4,3,0.266667,0.533333,0.400000,0.600000,0.303571
4,5,Chelsea,5,8,4,18.0,8.0,3,5,8,3,13.0,10.0,3,6,0.437500,0.687500,0.375000,1.937500,0.125000
5,6,Crystal Palace,6,8,2,9.0,15.0,1,7,8,3,11.0,14.0,0,4,0.312500,0.687500,0.062500,1.250000,-0.125000
6,7,Everton,7,7,4,15.0,11.0,1,6,8,5,11.0,8.0,3,7,0.600000,0.866667,0.266667,1.733333,-0.053571
7,8,Fulham,8,8,1,6.0,12.0,3,5,7,1,7.0,11.0,0,4,0.133333,0.600000,0.200000,0.866667,-0.017857
8,9,Leicester,9,8,3,11.0,12.0,2,6,8,6,18.0,8.0,3,7,0.562500,0.812500,0.312500,1.812500,-0.375000
9,10,Leeds,10,8,3,13.0,13.0,2,6,8,4,17.0,17.0,4,8,0.437500,0.875000,0.375000,1.875000,-0.125000
10,11,Liverpool,11,8,7,21.0,8.0,2,6,7,2,16.0,12.0,2,7,0.600000,0.866667,0.266667,2.466667,0.589286
11,12,Man City,12,7,4,14.0,7.0,4,3,7,3,7.0,5.0,3,5,0.500000,0.571429,0.500000,1.500000,0.142857
12,13,Man Utd,13,8,3,10.0,12.0,4,4,7,6,21.0,11.0,0,7,0.600000,0.733333,0.266667,2.066667,-0.482143
13,14,Newcastle,14,7,3,9.0,13.0,0,7,7,2,8.0,11.0,2,5,0.357143,0.857143,0.142857,1.214286,0.142857
14,15,Sheffield Utd,15,8,0,4.0,12.0,0,8,8,0,4.0,15.0,0,4,0.000000,0.750000,0.000000,0.500000,0.000000
15,16,Southampton,16,8,4,13.0,9.0,5,3,8,3,12.0,10.0,2,6,0.437500,0.562500,0.437500,1.562500,0.125000
16,17,Spurs,17,7,3,10.0,8.0,2,5,8,4,16.0,7.0,3,7,0.466667,0.800000,0.333333,1.733333,-0.071429
17,18,West Brom,18,8,1,5.0,20.0,2,6,8,0,6.0,15.0,0,5,0.062500,0.687500,0.125000,0.687500,0.125000
18,19,West Ham,19,8,3,12.0,10.0,2,6,8,3,11.0,11.0,3,6,0.375000,0.750000,0.312500,1.437500,0.000000
19,20,Wolves,20,8,3,9.0,8.0,2,6,8,3,6.0,13.0,2,4,0.375000,0.625000,0.250000,0.937500,0.000000

In [83]:
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,None,False,0,1190,1210,1170,1210,1190,1200,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,None,False,0,1150,1160,1150,1150,1180,1210,2
2,36,0,None,3,0,Brighton,0,0,0,BHA,...,None,False,0,1080,1100,1150,1180,1090,1100,131
3,90,0,None,4,0,Burnley,0,0,0,BUR,...,None,False,0,1050,1080,1120,1190,1010,1030,43
4,8,0,None,5,0,Chelsea,0,0,0,CHE,...,None,False,0,1260,1280,1240,1280,1270,1310,4
5,31,0,None,6,0,Crystal Palace,0,0,0,CRY,...,None,False,0,1110,1150,1100,1150,1020,1050,6
6,11,0,None,7,0,Everton,0,0,0,EVE,...,None,False,0,1180,1210,1150,1170,1210,1250,7
7,54,0,None,8,0,Fulham,0,0,0,FUL,...,None,False,0,1000,1020,1020,1030,1020,1020,34
8,13,0,None,9,0,Leicester,0,0,0,LEI,...,None,False,0,1220,1240,1190,1190,1200,1180,26
9,2,0,None,10,0,Leeds,0,0,0,LEE,...,None,False,0,1100,1130,1060,1110,1130,1160,9
10,14,0,None,11,0,Liverpool,0,0,0,LIV,...,None,False,0,1320,1360,1240,1320,1330,1350,10
11,43,0,None,12,0,Man City,0,0,0,MCI,...,None,False,0,1310,1360,1260,1320,1330,1350,11
12,1,0,None,13,0,Man Utd,0,0,0,MUN,...,None,False,0,1230,1230,1220,1230,1250,1260,12
13,4,0,None,14,0,Newcastle,0,0,0,NEW,...,None,False,0,1100,1130,1100,1120,1010,1060,23
14,49,0,None,15,0,Sheffield Utd,0,0,0,SHU,...,None,False,0,1070,1100,1110,1130,1010,1050,18
15,20,0,None,16,0,Southampton,0,0,0,SOU,...,None,False,0,1150,1180,1140,1200,1110,1160,20
16,6,0,None,17,0,Spurs,0,0,0,TOT,...,None,False,0,1270,1280,1190,1240,1280,1320,21
17,35,0,None,18,0,West Brom,0,0,0,WBA,...,None,False,0,1010,1030,1020,1020,1000,1010,36
18,21,0,None,19,0,West Ham,0,0,0,WHU,...,None,False,0,1140,1170,1150,1160,1170,1180,25
19,39,0,None,20,0,Wolves,0,0,0,WOL,...,None,False,0,1160,1190,1180,1220,1100,1170,38